class HelpPrinter:

    def help_latex():
        print("""
Picture:
    \insertpicture[<reference>]{<image_name>}{<width>}{<Description>}

Graph:
    \insertgraph[<reference>]{<graphname_name>}{<width>}{<Description>}

Table:
    \begin{inserttable}[<reference>]{|l|c|r|}{<Description>}
        \hline
        Here       & is      & some     \\ \hline
        ultimately & amazing & example. \\ \hline
    \end{inserttable}

Aligned multi row math:
    \\begin{equation} \label{<reference>}
    \\begin{aligned}
        y'''+7y''+6y' & = u'+3u \\\\
                 G(s) & = \\frac{s+3}{s^3+7s^2+6s}
    \end{aligned}
    \end{equation}

Music notation with musixtex package.
""", sep="")

    def help_settings():
        print("""

""")

    def help_commands():
        print("""
build
     Is default command. The command can have as parameter number of a file
     in the content folder if files are alphanumerically sorted. Numbers
     may be separated by "," as elements or by "-" as range. Default value
     is all files. Prefix "n" for files print every file on new page.

clean
    Delete temporary files.

clear
    Delete temporary files and created pdf.

pack
    Broken in this time.

encrypt
    Broken in this time.

cleanup
    Delete temporary latex files which are not generated by this instance.

help
    Print help.

run


init
    Create basic settings and folders for start new project.
""", sep="")

    def help(arg):
        if arg == "" or arg == "commands":
            HelpPrinter.help_commands()
            return
        if arg == "" or arg == "latex":
            HelpPrinter.help_latex()
            return
        if arg == "" or arg == "settings":
            HelpPrinter.help_settings()
            return
        print("Unknown help option.")
        HelpPrinter.help_commands()
